### ISSUE TITLE
Official extension now available 🌟 

### ISSUE THREAD

**Issue by fregante** [ngyuki/vscode-ghosttext#10]
Hello, I finally published the official extension for VS Code:

- https://github.com/fregante/GhostText-for-VSCode
- https://marketplace.visualstudio.com/items?itemName=fregante.ghost-text

I invite you to test it out, report any issues you see and contribute, if you have time. This is meant to replace the 3 forks currently available on the marketplace with a single, maintained, official version.

**Comment by ngyuki** [comment]
Sorry for the late reply.
I am not actively maintaining this and would like to deprecate it extension.

https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-5446706

**Comment by fregante** [comment]
Thank you!
